#+title: Git Mastery
#+author: Atri Hegde, Annie Tse

* Preface

* Table of Contents :TOC:
- [[#preface][Preface]]
- [[#chapters][Chapters]]
  - [[#introduction-to-linux][Introduction to Linux.]]
  - [[#git][Git]]
  - [[#problem-to-solve][Problem to solve.]]

* Chapters
** Introduction to Linux.
1. Installing WSL/Linux.
2. Introduction to BASH.

   Welcome to your introduction to BASH. Refer to this as a cheat sheet for your terminal commands.

   Change directory.
   #+BEGIN_SRC
   cd ..     # back a directory
   cd foo    # enter directory
   cd ~      # home directory
   #+END_SRC

  Listing files/directories in directory.
   #+begin_src
   ls      # lists files in directory
   ls -a   # lists all files(incluing hidden) in directory
   ls -l   # lists in londform
   #+end_src

   Removing
   #+begin_src
   rm foo      # removes file or empty directory
   rm -rf foo  # removes non-emtpy directory
   #+end_src

   Move/Copy (files/directories)
   #+begin_src
   mv foo ~/repos/foo # moves file or directory to location of second param
   cp foo ~/repos/foo # copies file or directory to location of second param
   #+end_src

   New directory
   #+begin_src
   mkdir foo   # makes new directory if does not already exists in current directory
   #+end_src

   New file
   #+begin_src
   touch foo.txt   # creates new file if does not already exist
   #+end_src

3. Package Manager.

    Package Manager is exactly how it sounds. It manages your packages when you are downloading something. Due to dependencies and updates to individual packages, it handles all these updates for you when updating or downloading, individually fetching and installing from the source list.

4. Nix: Package manager.
5. Installing a Java development environment.
** Git
1. Install and configure git.
2. GitHub, GitLab vs git.
3. SSH Keys, PGP Keys.
4. Commits, commit logs, revert commits.
5. Branches, merging
** Problem to solve.
We can use any language you want, but we will do this in Java.
Check [[./problem-sheet.org]]
